#!/bin/bash
echo "Compling..."
compilor="ifort"
sourcecode="DiagMC.f90"
target="gamma3.exe"

if [ -n "$1" ]
then
  if [ $1 = "-g" ] || [$1 = "g" ]; then
	    $compilor $sourcecode -o $target -g
			echo "Debug version done!"
  #elif []
	else
	    $compilor $sourcecode -O3 -o $target
			echo "Done!"
	fi
else
  $compilor $sourcecode -O3 -o $target
	echo "Done!"
fi
